version: '3'

networks:
  template_docker:
    ipam:
      config:
        - subnet: 190.20.200.1/24

services:
  db:
    build: 
      context: .
      dockerfile: mysql.dockerfile
    command: mysqld --innodb-large-prefix=1 --innodb-file-per-table=1 --default-authentication-plugin=mysql_native_password --innodb_file_format=Barracuda
    environment:
      MYSQL_ROOT_PASSWORD: yh24RE9l7vQt
      MYSQL_USER: test
      MYSQL_PASSWORD: 3cgcoG5JR9fg
      MYSQL_TCP_PORT: 3307
    volumes:
      - my_template_docker:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3307
    networks:
      template_docker:
        ipv4_address: 190.20.200.21
  web:
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DB_HOST: 190.20.200.21
      DB_PORT: 3307
      DB_USER: test
      DB_PASSWORD: 3cgcoG5JR9fg
    networks:
      - template_docker
  redis:
      image: "redis:alpine"
      command: --port 6385
      expose:
          - 6385
      ports:
          - 6385:6385
      networks:
          template_docker:
              ipv4_address: 190.20.200.22
volumes:
  gem_cache:
  my_template_docker:
    external: true